- type: entity
  parent: ClothingBackpackERTSecurity
  id: ClothingBackpackADTBlueShieldOfficerFilled
  components:
    - type: Storage
      maxItemSize: Huge
      grid:
      - 0,0,6,3
    - type: StorageFill
      contents:
        # - id: MedkitBruteFilled
        - id: Zipties
          amount: 3
        #- id: WeaponDisabler
        - id: Stunbaton
        # - id: HandheldCrewMonitor
        # - id: MagazinePistolSubMachineGun
        # - id: MagazinePistolSubMachineGun
        # - id: MagazinePistolSubMachineGunRubber
        # - id: MagazinePistolSubMachineGunRubber
        #- id: WeaponSubMachineGunDrozdRubber
        #- id: WeaponPulsePistol
        #- id: GrenadeFlashBang
        #- id: GrenadeFlashBang
        #- id: GrenadeFlashBang
        - id: BoxSurvivalSecurity
        # - id: BlueShieldBox
        - id: BlueShieldsuit
        - id: OxygenTankFilled
    - type: Sprite
      sprite: ADT/Clothing/Back/blueshield_backpack.rsi

